linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   install:
     - chmod +x .ci/travis/install.sh
     - .ci/travis/install.sh
     - mkdir $HOME/.conan/hooks
     - cp hook/deterministic-build.py $HOME/.conan/hooks/deterministic-build.py
   before_script:
     - conan profile new default --detect
     - conan profile update settings.compiler.libcxx=libstdc++11 default
     - conan config set hooks.deterministic-build
     - cat $HOME/.conan/conan.conf
     - ls $HOME/.conan/hooks

osx: &osx
   os: osx
   language: generic
   install:
     - chmod +x .ci/travis/install.sh
     - .ci/travis/install.sh
   before_script:
     - eval "$(pyenv init -)"
     - pyenv activate conan

matrix:
   include:
      - stage: Linux builds
        name: Getting started
        <<: *linux
        env: FOLDER=scripts

script:
 - cd "${FOLDER}"
 - chmod +x check.sh
 - ./check.sh