linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   compiler: gcc-8
   install:
     - chmod +x .ci/travis/install.sh
     - .ci/travis/install.sh
     - mkdir $HOME/.conan/hooks
     - cp hook/deterministic-build.py $HOME/.conan/hooks/deterministic-build.py
   before_script:
     - conan profile new default --detect
     - conan profile update settings.compiler.libcxx=libstdc++11 default
     - conan config set hooks.deterministic-build
     - conan config set general.revisions_enabled=True
     - cat $HOME/.conan/conan.conf
     - ls $HOME/.conan/hooks
   before_install:
     - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
     - sudo apt update
     - sudo apt-get install gcc-8 g++-8
     - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
     - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

osx: &osx
   os: osx
   language: generic
   install:
     - chmod +x .ci/travis/install.sh
     - .ci/travis/install.sh
     - mkdir $HOME/.conan/hooks
     - cp hook/deterministic-build.py $HOME/.conan/hooks/deterministic-build.py
     - brew install md5sha1sum 
   before_script:
     - eval "$(pyenv init -)"
     - pyenv activate conan
     - conan config set hooks.deterministic-build
     - conan config set general.revisions_enabled=True
     - cat $HOME/.conan/conan.conf
     - ls $HOME/.conan/hooks

matrix:
   include:
      - stage: Linux builds
        sudo: true
        name: Deterministic build
        <<: *linux
        env: FOLDER=scripts
      - stage: Macos builds
        sudo: true
        name: Deterministic build
        <<: *osx
        env: FOLDER=scripts

script:
 - cd "${FOLDER}"
 - chmod +x check.sh
 - ./check.sh