build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan Getting Started
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
          PROJECT_DIR: scripts
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
          PROJECT_DIR: scripts

install:
  - md C:\Users\appveyor\.conan\hooks
  - xcopy hook\deterministic-build.py C:\Users\appveyor\.conan\hooks
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - conan user
  - conan config set hooks.deterministic-build
  - conan config set general.revisions_enabled=True

test_script:
  - cd %PROJECT_DIR%
  - check.bat